# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_dataQuery_v102.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1276, 871)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_countTail = QtWidgets.QLabel(Form)
        self.label_countTail.setObjectName("label_countTail")
        self.gridLayout_4.addWidget(self.label_countTail, 2, 9, 1, 1)
        self.lineEd_pagInfo = QtWidgets.QLineEdit(Form)
        self.lineEd_pagInfo.setMaxLength(32767)
        self.lineEd_pagInfo.setObjectName("lineEd_pagInfo")
        self.gridLayout_4.addWidget(self.lineEd_pagInfo, 2, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.pushB_nextPag = QtWidgets.QPushButton(Form)
        self.pushB_nextPag.setObjectName("pushB_nextPag")
        self.gridLayout_4.addWidget(self.pushB_nextPag, 2, 13, 1, 1)
        self.pushB_fristPag = QtWidgets.QPushButton(Form)
        self.pushB_fristPag.setObjectName("pushB_fristPag")
        self.gridLayout_4.addWidget(self.pushB_fristPag, 2, 11, 1, 1)
        self.label_everyPag = QtWidgets.QLabel(Form)
        self.label_everyPag.setObjectName("label_everyPag")
        self.gridLayout_4.addWidget(self.label_everyPag, 2, 7, 1, 1)
        self.pushB_previousPag = QtWidgets.QPushButton(Form)
        self.pushB_previousPag.setObjectName("pushB_previousPag")
        self.gridLayout_4.addWidget(self.pushB_previousPag, 2, 12, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 3, 1, 1)
        self.pushB_endPag = QtWidgets.QPushButton(Form)
        self.pushB_endPag.setObjectName("pushB_endPag")
        self.gridLayout_4.addWidget(self.pushB_endPag, 2, 14, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 1, 1, 1)
        self.spinBox_pagShowRows = QtWidgets.QSpinBox(Form)
        self.spinBox_pagShowRows.setMaximum(25000)
        self.spinBox_pagShowRows.setProperty("value", 20000)
        self.spinBox_pagShowRows.setObjectName("spinBox_pagShowRows")
        self.gridLayout_4.addWidget(self.spinBox_pagShowRows, 2, 8, 1, 1)
        self.spinBox_pagGo = QtWidgets.QSpinBox(Form)
        self.spinBox_pagGo.setMaximum(999)
        self.spinBox_pagGo.setObjectName("spinBox_pagGo")
        self.gridLayout_4.addWidget(self.spinBox_pagGo, 2, 15, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 2, 2, 1, 1)
        self.pushB_goTo = QtWidgets.QPushButton(Form)
        self.pushB_goTo.setObjectName("pushB_goTo")
        self.gridLayout_4.addWidget(self.pushB_goTo, 2, 16, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_startTime = QtWidgets.QLabel(Form)
        self.label_startTime.setObjectName("label_startTime")
        self.gridLayout_2.addWidget(self.label_startTime, 0, 1, 1, 1)
        self.dateTimeEd_start = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEd_start.setObjectName("dateTimeEd_start")
        self.gridLayout_2.addWidget(self.dateTimeEd_start, 0, 2, 1, 1)
        self.pushB_query = QtWidgets.QPushButton(Form)
        self.pushB_query.setObjectName("pushB_query")
        self.gridLayout_2.addWidget(self.pushB_query, 1, 5, 1, 1)
        self.pushB_del = QtWidgets.QPushButton(Form)
        self.pushB_del.setObjectName("pushB_del")
        self.gridLayout_2.addWidget(self.pushB_del, 1, 9, 1, 1)
        self.pushB_ept_1 = QtWidgets.QPushButton(Form)
        self.pushB_ept_1.setObjectName("pushB_ept_1")
        self.gridLayout_2.addWidget(self.pushB_ept_1, 1, 8, 1, 1)
        self.label_totalHead = QtWidgets.QLabel(Form)
        self.label_totalHead.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_totalHead.setObjectName("label_totalHead")
        self.gridLayout_2.addWidget(self.label_totalHead, 4, 5, 1, 1)
        self.pushB_export = QtWidgets.QPushButton(Form)
        self.pushB_export.setObjectName("pushB_export")
        self.gridLayout_2.addWidget(self.pushB_export, 1, 7, 1, 1)
        self.label_endTime = QtWidgets.QLabel(Form)
        self.label_endTime.setObjectName("label_endTime")
        self.gridLayout_2.addWidget(self.label_endTime, 4, 1, 1, 1)
        self.label_dateRange = QtWidgets.QLabel(Form)
        self.label_dateRange.setObjectName("label_dateRange")
        self.gridLayout_2.addWidget(self.label_dateRange, 1, 0, 1, 1)
        self.dateTimeEd_end = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEd_end.setObjectName("dateTimeEd_end")
        self.gridLayout_2.addWidget(self.dateTimeEd_end, 4, 2, 1, 1)
        self.pushB_endTm = QtWidgets.QPushButton(Form)
        self.pushB_endTm.setObjectName("pushB_endTm")
        self.gridLayout_2.addWidget(self.pushB_endTm, 4, 3, 1, 1)
        self.label_unqHead = QtWidgets.QLabel(Form)
        self.label_unqHead.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_unqHead.setObjectName("label_unqHead")
        self.gridLayout_2.addWidget(self.label_unqHead, 4, 8, 1, 1)
        self.pushB_startTm = QtWidgets.QPushButton(Form)
        self.pushB_startTm.setObjectName("pushB_startTm")
        self.gridLayout_2.addWidget(self.pushB_startTm, 0, 3, 1, 1)
        self.label_unqVal = QtWidgets.QLabel(Form)
        self.label_unqVal.setObjectName("label_unqVal")
        self.gridLayout_2.addWidget(self.label_unqVal, 4, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 10, 1, 1)
        self.label_totalV = QtWidgets.QLabel(Form)
        self.label_totalV.setObjectName("label_totalV")
        self.gridLayout_2.addWidget(self.label_totalV, 4, 7, 1, 1)
        self.checkBox_case = QtWidgets.QCheckBox(Form)
        self.checkBox_case.setObjectName("checkBox_case")
        self.gridLayout_2.addWidget(self.checkBox_case, 1, 4, 1, 1)
        self.pushB_ept_2 = QtWidgets.QPushButton(Form)
        self.pushB_ept_2.setObjectName("pushB_ept_2")
        self.gridLayout_2.addWidget(self.pushB_ept_2, 1, 10, 1, 1)
        self.tableWid_battInfo = QtWidgets.QTableWidget(Form)
        self.tableWid_battInfo.setObjectName("tableWid_battInfo")
        self.tableWid_battInfo.setColumnCount(11)
        self.tableWid_battInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWid_battInfo.setHorizontalHeaderItem(10, item)
        self.gridLayout_2.addWidget(self.tableWid_battInfo, 6, 0, 1, 13)
        self.pushB_quit = QtWidgets.QPushButton(Form)
        self.pushB_quit.setObjectName("pushB_quit")
        self.gridLayout_2.addWidget(self.pushB_quit, 0, 12, 1, 1)
        self.comboB_selCase = QtWidgets.QComboBox(Form)
        self.comboB_selCase.setObjectName("comboB_selCase")
        self.comboB_selCase.addItem("")
        self.comboB_selCase.addItem("")
        self.gridLayout_2.addWidget(self.comboB_selCase, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 17)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_countTail.setText(_translate("Form", "条"))
        self.pushB_nextPag.setText(_translate("Form", "下一页"))
        self.pushB_fristPag.setText(_translate("Form", "首页"))
        self.label_everyPag.setText(_translate("Form", "每一页"))
        self.pushB_previousPag.setText(_translate("Form", "上一页"))
        self.pushB_endPag.setText(_translate("Form", "尾页"))
        self.pushB_goTo.setText(_translate("Form", "Go"))
        self.label_startTime.setText(_translate("Form", "起始时间："))
        self.pushB_query.setText(_translate("Form", "查 询"))
        self.pushB_del.setText(_translate("Form", "删 除"))
        self.pushB_ept_1.setText(_translate("Form", "PushButton"))
        self.label_totalHead.setText(_translate("Form", "总数目："))
        self.pushB_export.setText(_translate("Form", "导 出"))
        self.label_endTime.setText(_translate("Form", "终止时间："))
        self.label_dateRange.setText(_translate("Form", "日期范围："))
        self.pushB_endTm.setText(_translate("Form", "PushButton"))
        self.label_unqHead.setText(_translate("Form", "不合格数："))
        self.pushB_startTm.setText(_translate("Form", "PushButton"))
        self.label_unqVal.setText(_translate("Form", "0"))
        self.label_totalV.setText(_translate("Form", "0"))
        self.checkBox_case.setText(_translate("Form", "筛选条件"))
        self.pushB_ept_2.setText(_translate("Form", "PushButton"))
        item = self.tableWid_battInfo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序 号"))
        item = self.tableWid_battInfo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "料盘号码"))
        item = self.tableWid_battInfo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "托盘中编号"))
        item = self.tableWid_battInfo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "记    录    时   间"))
        item = self.tableWid_battInfo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "前称重"))
        item = self.tableWid_battInfo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "后称重"))
        item = self.tableWid_battInfo.horizontalHeaderItem(6)
        item.setText(_translate("Form", "比较下限"))
        item = self.tableWid_battInfo.horizontalHeaderItem(7)
        item.setText(_translate("Form", "比较上限"))
        item = self.tableWid_battInfo.horizontalHeaderItem(8)
        item.setText(_translate("Form", "注液量"))
        item = self.tableWid_battInfo.horizontalHeaderItem(9)
        item.setText(_translate("Form", "补液量"))
        item = self.tableWid_battInfo.horizontalHeaderItem(10)
        item.setText(_translate("Form", "状态"))
        self.pushB_quit.setText(_translate("Form", "关  闭"))
        self.comboB_selCase.setItemText(0, _translate("Form", "OK"))
        self.comboB_selCase.setItemText(1, _translate("Form", "NG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

