# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PortConfig.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 385)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 120, 421, 211))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineE_IP = QtWidgets.QLineEdit(self.tab)
        self.lineE_IP.setGeometry(QtCore.QRect(150, 50, 151, 20))
        self.lineE_IP.setObjectName("lineE_IP")
        self.lineE_tcpStation = QtWidgets.QLineEdit(self.tab)
        self.lineE_tcpStation.setGeometry(QtCore.QRect(150, 100, 151, 20))
        self.lineE_tcpStation.setObjectName("lineE_tcpStation")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.stopBitsCombo = QtWidgets.QComboBox(self.tab_2)
        self.stopBitsCombo.setGeometry(QtCore.QRect(160, 160, 97, 20))
        self.stopBitsCombo.setObjectName("stopBitsCombo")
        self.stopBitsCombo.addItem("")
        self.stopBitsCombo.addItem("")
        self.stopBitsCombo.addItem("")
        self.parityCombo = QtWidgets.QComboBox(self.tab_2)
        self.parityCombo.setGeometry(QtCore.QRect(160, 130, 97, 20))
        self.parityCombo.setObjectName("parityCombo")
        self.parityCombo.addItem("")
        self.parityCombo.addItem("")
        self.parityCombo.addItem("")
        self.parityCombo.addItem("")
        self.parityCombo.addItem("")
        self.portCombo = QtWidgets.QComboBox(self.tab_2)
        self.portCombo.setGeometry(QtCore.QRect(160, 10, 97, 20))
        self.portCombo.setObjectName("portCombo")
        self.addressSpinner = QtWidgets.QSpinBox(self.tab_2)
        self.addressSpinner.setGeometry(QtCore.QRect(160, 40, 91, 20))
        self.addressSpinner.setMaximum(256)
        self.addressSpinner.setProperty("value", 1)
        self.addressSpinner.setObjectName("addressSpinner")
        self.label_baudRate = QtWidgets.QLabel(self.tab_2)
        self.label_baudRate.setGeometry(QtCore.QRect(60, 70, 98, 20))
        self.label_baudRate.setObjectName("label_baudRate")
        self.label_parity = QtWidgets.QLabel(self.tab_2)
        self.label_parity.setGeometry(QtCore.QRect(60, 130, 98, 20))
        self.label_parity.setObjectName("label_parity")
        self.label_comPort = QtWidgets.QLabel(self.tab_2)
        self.label_comPort.setGeometry(QtCore.QRect(60, 10, 98, 20))
        self.label_comPort.setObjectName("label_comPort")
        self.label_dataBits = QtWidgets.QLabel(self.tab_2)
        self.label_dataBits.setGeometry(QtCore.QRect(60, 100, 98, 20))
        self.label_dataBits.setObjectName("label_dataBits")
        self.dataBitsCombo = QtWidgets.QComboBox(self.tab_2)
        self.dataBitsCombo.setGeometry(QtCore.QRect(160, 100, 97, 20))
        self.dataBitsCombo.setObjectName("dataBitsCombo")
        self.dataBitsCombo.addItem("")
        self.dataBitsCombo.addItem("")
        self.dataBitsCombo.addItem("")
        self.dataBitsCombo.addItem("")
        self.label_stopBits = QtWidgets.QLabel(self.tab_2)
        self.label_stopBits.setGeometry(QtCore.QRect(60, 159, 91, 21))
        self.label_stopBits.setObjectName("label_stopBits")
        self.label_address = QtWidgets.QLabel(self.tab_2)
        self.label_address.setGeometry(QtCore.QRect(60, 40, 98, 20))
        self.label_address.setObjectName("label_address")
        self.baudCombo = QtWidgets.QComboBox(self.tab_2)
        self.baudCombo.setGeometry(QtCore.QRect(160, 70, 97, 20))
        self.baudCombo.setObjectName("baudCombo")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.baudCombo.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushB_ok = QtWidgets.QPushButton(Dialog)
        self.pushB_ok.setGeometry(QtCore.QRect(210, 340, 75, 23))
        self.pushB_ok.setObjectName("pushB_ok")
        self.pushB_cancel = QtWidgets.QPushButton(Dialog)
        self.pushB_cancel.setGeometry(QtCore.QRect(320, 340, 75, 23))
        self.pushB_cancel.setObjectName("pushB_cancel")
        self.comb_Type = QtWidgets.QComboBox(Dialog)
        self.comb_Type.setGeometry(QtCore.QRect(150, 80, 141, 22))
        self.comb_Type.setObjectName("comb_Type")
        self.comb_Type.addItem("")
        self.comb_Type.addItem("")
        self.label_bgHeader = QtWidgets.QLabel(Dialog)
        self.label_bgHeader.setGeometry(QtCore.QRect(0, 0, 441, 51))
        self.label_bgHeader.setText("")
        self.label_bgHeader.setPixmap(QtGui.QPixmap(":/icon/Icon/Background_head.png"))
        self.label_bgHeader.setScaledContents(True)
        self.label_bgHeader.setObjectName("label_bgHeader")
        self.label_programName = QtWidgets.QLabel(Dialog)
        self.label_programName.setGeometry(QtCore.QRect(40, 0, 311, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_programName.setFont(font)
        self.label_programName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_programName.setObjectName("label_programName")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.parityCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "IP Address:"))
        self.label_3.setText(_translate("Dialog", "Address:"))
        self.lineE_IP.setText(_translate("Dialog", "192.168.10.11"))
        self.lineE_tcpStation.setText(_translate("Dialog", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.stopBitsCombo.setItemText(0, _translate("Dialog", "1"))
        self.stopBitsCombo.setItemText(1, _translate("Dialog", "3"))
        self.stopBitsCombo.setItemText(2, _translate("Dialog", "2"))
        self.parityCombo.setCurrentText(_translate("Dialog", "Even"))
        self.parityCombo.setItemText(0, _translate("Dialog", "None"))
        self.parityCombo.setItemText(1, _translate("Dialog", "Even"))
        self.parityCombo.setItemText(2, _translate("Dialog", "Odd"))
        self.parityCombo.setItemText(3, _translate("Dialog", "Space"))
        self.parityCombo.setItemText(4, _translate("Dialog", "Mark"))
        self.label_baudRate.setText(_translate("Dialog", "Baud Rate:"))
        self.label_parity.setText(_translate("Dialog", "Parity:"))
        self.label_comPort.setText(_translate("Dialog", "COM Port:"))
        self.label_dataBits.setText(_translate("Dialog", "Data Bits:"))
        self.dataBitsCombo.setCurrentText(_translate("Dialog", "5"))
        self.dataBitsCombo.setItemText(0, _translate("Dialog", "5"))
        self.dataBitsCombo.setItemText(1, _translate("Dialog", "6"))
        self.dataBitsCombo.setItemText(2, _translate("Dialog", "7"))
        self.dataBitsCombo.setItemText(3, _translate("Dialog", "8"))
        self.label_stopBits.setText(_translate("Dialog", "Stop Bits:"))
        self.label_address.setText(_translate("Dialog", "Address :"))
        self.baudCombo.setCurrentText(_translate("Dialog", "1200"))
        self.baudCombo.setItemText(0, _translate("Dialog", "1200"))
        self.baudCombo.setItemText(1, _translate("Dialog", "2400"))
        self.baudCombo.setItemText(2, _translate("Dialog", "4800"))
        self.baudCombo.setItemText(3, _translate("Dialog", "9600"))
        self.baudCombo.setItemText(4, _translate("Dialog", "19200"))
        self.baudCombo.setItemText(5, _translate("Dialog", "38400"))
        self.baudCombo.setItemText(6, _translate("Dialog", "57600"))
        self.baudCombo.setItemText(7, _translate("Dialog", "115200"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
        self.pushB_ok.setText(_translate("Dialog", "OK"))
        self.pushB_cancel.setText(_translate("Dialog", "Cancel"))
        self.comb_Type.setItemText(0, _translate("Dialog", "TCP"))
        self.comb_Type.setItemText(1, _translate("Dialog", "RS485"))
        self.label_programName.setText(_translate("Dialog", "Port Config"))
        self.label.setText(_translate("Dialog", "Link Type :"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

